version: 2.1

orbs:
  node: circleci/node@4.7
  codecov: codecov/codecov@3.0.0

jobs:
  build-and-test:
    docker:
      - image: cimg/node:18.12
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run tests
          command: npm test
      - codecov/upload:
          file: coverage/lcov.info 
          validate_url: true 

workflows:
  run-unit-tests:
    jobs:
      - build-and-test
